language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.1
matrix:
  include:
    - rvm: 2.1
      env: "RAILS_VERSION=4.2.4"

notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  - "RAILS_VERSION=4.1.13"

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
