language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
env:
  - "RAILS_VERSION=4.2.6"
  - "RSOLR_VERSION=2.0.0.pre1"
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
