language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
matrix:
  include:
    - rvm: 2.2.4
      env: "RAILS_VERSION=4.1.14"

notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  - "RAILS_VERSION=4.2.6"

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
