language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1

gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.beta.gemfile


notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
