language: ruby
rvm:
  - 2.3.1


matrix:
  include:
    - rvm: 2.2.5
      env: RAILS_VERSION=4.2.7.1
    - rvm: 2.1.10
      env: RAILS_VERSION=4.2.7.1

notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
