development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8984/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:4567
  base_path: <%= "/test#{SecureRandom.hex}" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
