development:
  default:
    url: http://localhost:8983/solr/hydra-dev
  full_text:
    url: http://localhost:8983/solr/development
test:
  default:
    url: http://localhost:8985/solr/hydra-test
  full_text:
    url: http://localhost:8985/solr/test
production:
  default:
    url: http://localhost:8080/solr/production
  full_text:
    url: http://localhost:8080/solr/production
